fix(TS-891): init unWatch to noop  --for non-modal events that use itt-iframe, unWach is never  defined, thus trying to call unWatch() - to deregister the watch on  $destroy() - results in a TypeError - unWatch is not a function.